=== camenduru/pyramid-flow-t2v-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Pyramidal Flow Matching for Efficient Video Generative Modeling",
      "author": "Yang Jin, Zhicheng Sun, Ningyuan Li, Kun Xu, Kun Xu, Hao Jiang, Nan Zhuang, Quzhe Huang, Yang Song, Yadong Mu, Zhouchen Lin",
      "code": "https://github.com/jy0205/Pyramid-Flow",
      "paper": "https://arxiv.org/abs/2410.05954",
      "page": "https://pyramid-flow.github.io/",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/pyramid-flow-t2v.ipynb",
      "tags": [
        "Text to Video"
      ],
      "widget": "readme"
    },
    "prompt": {
      "type": "string",
      "description": "Prompt",
      "widget": "textarea"
    },
    "num_inference_steps": {
      "type": "integer",
      "description": "Num Inference Steps",
      "widget": "hidden"
    },
    "video_num_inference_steps": {
      "type": "integer",
      "description": "Video Num Inference Steps",
      "widget": "hidden"
    },
    "width": {
      "type": "integer",
      "description": "Width",
      "widget": "hidden"
    },
    "height": {
      "type": "integer",
      "description": "Height",
      "widget": "hidden"
    },
    "temp": {
      "type": "integer",
      "description": "Temp",
      "widget": "hidden"
    },
    "guidance_scale": {
      "type": "number",
      "description": "Guidance Scale",
      "widget": "hidden"
    },
    "video_guidance_scale": {
      "type": "number",
      "description": "Video Guidance Scale",
      "widget": "hidden"
    },
    "seed": {
      "type": "integer",
      "description": "if 0 random"
    },
    "fps": {
      "type": "integer",
      "description": "fps",
      "widget": "hidden"
    },
    "example": {
      "type": "string",
      "image1": "https://files.catbox.moe/6t10xv.mp4",
      "image2": "https://files.catbox.moe/q279zp.mp4",
      "image3": "https://files.catbox.moe/2fpr5t.mp4",
      "image4": "https://files.catbox.moe/oy5df2.mp4",
      "video_aspect_ratio": "60%",
      "line1": "Video size: 1280x768 pixels",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/pyramid-flow-t2v-tost/model.json
{
    "prompt": "A movie trailer featuring the adventures of the 30 year old space man wearing a red wool knitted motorcycle helmet, blue sky, salt desert, cinematic style, shot on 35mm film, vivid colors",
    "num_inference_steps": 20,
    "video_num_inference_steps": 10,
    "width": 1280,
    "height": 768,
    "temp": 16,
    "guidance_scale": 9.0,
    "video_guidance_scale": 5.0,
    "seed": 42,
    "fps":24
}
